### ISSUE TITLE
benchmark/suite unexpected behavior

### ISSUE THREAD

**Issue by Char15Xu** [abcsys/libem#67]
1. When running benchmark/suite/llama3.py, get keyError:name in /libem/libem/prepare/datasets/amazon_google.py.
2. Setting `args.no-schema = True` does not remove the structured format as expected. (currently need to set `args.schema = False` to make it work)

**Comment by daiwaid** [comment]
1. Cannot reproduce. There is no `name` key referenced in /libem/libem/prepare/datasets/amazon_google.py. Can you provide a full error log?
2. Intended behavior, the `--no-schema` flag is mapped to `args.schema'. The flag is named that way because `args.schema` is on by default.

**Comment by Char15Xu** [comment]
1. when running benchmark/suite/llama3.py, the following error happens after finished running abt-buy dataset:
```
Traceback (most recent call last):
  File "/Users/charlesxu/libem/benchmark/suite/llama3.py", line 96, in <module>
    reports = run_benchmark()
  File "/Users/charlesxu/libem/benchmark/suite/llama3.py", line 33, in run_benchmark
    report = run.run(args)
  File "/Users/charlesxu/libem/benchmark/run.py", line 18, in run
    return benchmark_func(args)
  File "/Users/charlesxu/libem/benchmark/classic/amazon_google.py", line 43, in run
    test_set = list(test_set)
  File "/Users/charlesxu/libem/libem/prepare/datasets/amazon_google.py", line 48, in read
    parsed_data['left'] = {field: left_values[field] for field in fields}
  File "/Users/charlesxu/libem/libem/prepare/datasets/amazon_google.py", line 48, in <dictcomp>
    parsed_data['left'] = {field: left_values[field] for field in fields}
KeyError: 'name'
```
2. i think `python benchmark/suite/llama3.py --no-schema` does not remove the structure format. Is setting `args.schema = False` the only way to remove structure format?

**Comment by daiwaid** [comment]
1. There shouldn't be a `name` field in the amazon-google dataset, make sure your libem-sample-data folder is up to date and make sure you aren't adding/modifying the `args.kwargs['fields']` field (try checking if that field exists and what it contains at the beginning of benchmark/classic/amazon_google.py and see if it's been modified to include an additional `name` field, you can see what the `fields` dict is supposed to be set to by default on line 33: `["title", "manufacturer", "price"]`.
2. the flags are only accepted in the command line if you run `python benchmark/run.py` or `python -m benchmark.run`. I would suggest adding your benchmark to the benchmark/__init__.py file and initiate benchmarks using `python -m benchmark.run -n <your-benchmark>`.

**Comment by Char15Xu** [comment]
1. My dataset is updated and `name` is not a field in the amazon-google dataset. However, I added `print(fields)` on line 21 in ` libem/prepare/datasets/amazon_google.py` . It printed out `['name', 'description', 'price']`. I assume that `kwargs['fields']` kept the previous fields from `abt-buy` which caused `name` to appear in the dataset? 
Here is the full error log:
```
Running amazon-google...
Namespace(name='amazon-google', input_file='', output_file='', num_pairs=-1, start_index=0, shuffle=True, schema=True, block=False, match=True, seed=42, quiet=False, kwargs={'schema': True, 'version': 1, 'keep_null': True, 'price_diff': False, 'fields': ['name', 'description', 'price']}, log=False, icl='similar-shots', num_shots=0, model='llama3', temperature=0, batch_size=1, browse=False, cot=False, confidence=False, similarity=-1, rules='', sync=False, debug=False, guess=False)
['name', 'description', 'price']
Traceback (most recent call last):
  File "/Users/charlesxu/libem/benchmark/suite/llama3.py", line 95, in <module>
    reports = run_benchmark()
  File "/Users/charlesxu/libem/benchmark/suite/llama3.py", line 32, in run_benchmark
    report = run.run(args)
  File "/Users/charlesxu/libem/benchmark/run.py", line 18, in run
    return benchmark_func(args)
  File "/Users/charlesxu/libem/benchmark/classic/amazon_google.py", line 43, in run
    test_set = list(test_set)
  File "/Users/charlesxu/libem/libem/prepare/datasets/amazon_google.py", line 49, in read
    parsed_data['left'] = {field: left_values[field] for field in fields}
  File "/Users/charlesxu/libem/libem/prepare/datasets/amazon_google.py", line 49, in <dictcomp>
    parsed_data['left'] = {field: left_values[field] for field in fields}
KeyError: 'name'
```

**Comment by daiwaid** [comment]
Ah yes, you are right. The /classic benchmarks are not designed to be run consecutively using the same `args` variable. You should reset/re-generate the `args` variable after each dataset to avoid the cross-contamination you've observed.

**Comment by Char15Xu** [comment]
Got it! Thanks
